services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtual-shop-dev
    environment:

      SPRING_PROFILES_ACTIVE: dev
      

      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - virtual-shop-network

    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  virtual-shop-network:
    driver: bridge
